language: php

php:
  - 7.2

addons:
  chrome: stable

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database base_tests;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk


notifications:
  email:
    recipients:
      - felipe-guzman.c@hotmail.com
    on-success: always
    on-failure: always
